#!/bin/sh

{% if ansible_facts.system == 'Linux' %}
# skip in favour of systemd timer
if [ -d /run/systemd/system ]; then
    exit 0
fi
{% endif %}

# this cronjob persists removals (but not purges)
if [ ! -x "{{ sys_logrotate_bin_path }}" ]; then
    exit 0
fi

{{ sys_logrotate_bin_path }} {{ sys_logrotate_conf }}
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit $EXITVALUE
