---
network:
  version: 2
  renderer: networkd
  ethernets:
{% if want_sys_ipv4 and ansible_default_ipv4 and ansible_default_ipv4.interface %}
    {{ ansible_default_ipv4.interface }}:
      addresses:
        - {{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) | ipsubnet }}
      gateway4: {{ ansible_default_ipv4.gateway }}
      nameservers:
          search: {{ sys_domain_search }}
          addresses: {{ sys_domain_nameservers.ipv6 }}
#          options: {{ ansible_dns.options }}
      dhcp4: no
      dhcp6: no
{% endif %}
{% if want_sys_ipv6 and ansible_default_ipv6 and ansible_default_ipv6.interface %}
    {{ ansible_default_ipv6.interface }}:
      addresses:
        - {{ (ansible_default_ipv6.address + '/' + ansible_default_ipv6.netmask) | ipsubnet }}
      gateway4: {{ ansible_default_ipv6.gateway }}
      nameservers:
          search: {{ sys_domain_search }}
          addresses: {{ sys_domain_nameservers.ipv6 }}
#          options: {{ ansible_dns.options }}
      dhcp4: no
      dhcp6: no
{% endif %}
