---
network:
  version: {{ sys_network_netplan_version }}
  renderer: {{ sys_network_netplan_static_renderer }}


{% set bridge_interfaces = sys_network_interfaces | selectattr('type', 'defined') | selectattr('type', 'equalto', 'bridge') | list %}
{% set ethernet_interfaces = sys_network_interfaces | selectattr('type', 'defined') | selectattr('type', 'equalto', 'ethernet') | list %}

{% if ethernet_interfaces %}
  ethernets:
{%   for interface in ethernet_interfaces %}
    {{ interface.dev }}:
      dhcp4: {{ interface.dhcp4 | bool | lower }}
      dhcp6: {{ interface.dhcp4 | bool | lower }}
{%     if 'addresses' in interface and interface.addresses %}
      addresses: {{ interface.addresses }}
{%     endif %}
{%     if interface.get('dns', true) %}
      nameservers:
{% set local_nameservers = interface.get('dns_nameservers', sys_domain_default_nameservers.ipv4 + sys_domain_default_nameservers.ipv6) %}
{%       if local_nameservers %}
          addresses: {{ local_nameservers }}
{%       endif %}
{%       if interface.get('dns_search', false) %}
          search: {{ interface.dns_search }}
{%       endif %}
{%     endif %}
{%     if interface.get('routes', false) %}
      routes:
{%       for route in interface.routes %}
        - on-link: {{ route.on_link | default(true) }}
          to: {{ route.to }}
          via: {{ route.via }}
{%       endfor %}
{%     endif %}
{%   endfor %}
{% endif %}

{% if bridge_interfaces %}
  bridges:
{%   for interface in bridge_interfaces %}
    {{ interface.dev }}:
      dhcp4: {{ interface.dhcp4 | bool | lower }}
      dhcp6: {{ interface.dhcp4 | bool | lower }}
{%     if 'interfaces' in interface and interface.interfaces %}
      interfaces: {{ interface.interfaces }}
{%     endif %}
{%     if 'addresses' in interface and interface.addresses %}
      addresses: {{ interface.addresses }}
{%     endif %}
{%     if interface.get('dns', true) %}
      nameservers:
{% set local_nameservers = interface.get('dns_nameservers', sys_domain_default_nameservers.ipv4 + sys_domain_default_nameservers.ipv6) %}
{%       if local_nameservers %}
          addresses: {{ local_nameservers }}
{%       endif %}
{%       if interface.get('dns_search', false) %}
          search: {{ interface.dns_search }}
{%       endif %}
{%     endif %}
{%     if interface.get('routes', false) %}
      routes:
{%       for route in interface.routes %}
        - on-link: {{ route.on_link | default(true) }}
          to: {{ route.to }}
          via: {{ route.via }}
{%       endfor %}
{%     endif %}
{%   endfor %}
{% endif %}
