---

- block:
    - name: compute package list
      set_fact:
        sys_computed_developer_packages: "{{ \
                 (sys_packages['developer']['common'] | d([])) \
                 + (sys_packages['developer'][ansible_distribution] | d([]))
              }}"

    - block:
        - name: apt based update
          apt:
            upgrade: "yes"
            update_cache: yes
            cache_valid_time: "{{ sys_packages_cache_ttl }}"

        - name: "apt install developer packages"
          apt:
            name: "{{ sys_computed_developer_packages }}"
            state: latest
            update_cache: yes
            cache_valid_time: "{{ sys_packages_cache_ttl }}"
            autoremove: yes

      when: ansible_pkg_mgr == 'apt'

  when:
    - want_developer | d(no)
