---

- block:

    - include_tasks: nftables.yml

    - include_tasks: iptables.yml

    - include_tasks: firewalld.yml

    - include_tasks: ufw.yml

  when: (is_router | d(false)) or (is_server | d(false)) or want_sys_security
