---

- name: set sys_network_mode
  block:
    - name: set sys_network_mode to router
      set_fact:
        sys_network_mode: router
      when: sys_network_mode is not defined and is_router is defined and is_router

    - name: set sys_network_mode to static
      set_fact:
        sys_network_mode: static
      when: sys_network_mode is not defined and hosttype == 'server'

    - name: set sys_network_mode to desktop
      set_fact:
        sys_network_mode: desktop
      when: sys_network_mode is not defined and hosttype == 'desktop'

    - name: set sys_network_mode to network-manager
      set_fact:
        sys_network_mode: dynamic
      when: sys_network_mode is not defined


- name: set network configuration with netplan
  include_tasks: netplan.yml
  when: ansible_distribution == 'Ubuntu'
