---

- name: set sys_network_mode
  block:
    - name: set sys_network_mode to static
      set_fact:
        sys_network_mode: static
      when: sys_network_mode is not defined and is_router is defined and is_router

    - name: set sys_network_mode to static
      set_fact:
        sys_network_mode: static
      when: sys_network_mode is not defined and host_type == 'server'

    - name: set sys_network_mode to network_manager
      set_fact:
        sys_network_mode: network_manager
      when: sys_network_mode is not defined and host_type == 'workstation'

    - name: set sys_network_mode to dynamic
      set_fact:
        sys_network_mode: dynamic
      when: sys_network_mode is not defined


- name: configure network with netplan
  include_tasks: netplan.yml
  when: ansible_distribution == 'Ubuntu'


- name: configure wifi
  include_tasks: network_wifi.yml
