---

- name: deploy sudoers
  template:
    src: 'sudoers.d/{{ item.name }}'
    dest: '{{ sys_sudoers_d }}/{{ item.order }}_{{ item.name }}'
    owner: root
    group: "{{ root_group }}"
    mode: 0440
    validate: 'sh -c "cat {{ sys_sudoers_conf }} %s | visudo -cf-"'
  loop: "{{ sys_sudoers }}"
