---

- name: compute sysctls
  set_fact:
    sys_sysctls_computed: "{{ (sys_sysctls_computed|d([])) + [item] }}"
  loop: "{{ sys_sysctls + sys_sysctls_base }}"
  when: item.name not in (sys_sysctls_computed|d([])) | map(attribute='name') | list


- name: set sysctls
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: "{{ sys_sysctl_conf }}"
  loop: "{{ sys_sysctls_computed }}"
