---

- include_tasks: _sysctl.yml
  loop: "{{ (sys_sysctls_base|d([])) + (sys_sysctls_group|d([])) + (sys_sysctls_host|d([])) }}"
  loop_control:
    loop_var: _sysctl
  vars:
    _sysctl_conf: "{{ sys_sysctl_conf }}"
    _sysctl_conf_d: "{{ sys_sysctl_conf_d }}"
